/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.KetQuaController;
import Model.KetQuaHocTap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author PV
 */
public class KetQuaHocTapSV extends javax.swing.JFrame {

    /**
     * Creates new form KetQuaHocTapSV
     */
    public KetQuaHocTapSV() {
        initComponents();
        hienThi();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbHoTen = new javax.swing.JLabel();
        jlbMaSV = new javax.swing.JLabel();
        jlbLop = new javax.swing.JLabel();
        jbtThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kết quả học tập");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlbHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbHoTen.setText("jLabel1");

        jlbMaSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMaSV.setText("jLabel2");

        jlbLop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbLop.setText("jLabel3");

        jbtThoat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jbtThoat.setText("Thoát");
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Kết quả học tập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtThoat)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaSV)
                            .addComponent(jlbLop)
                            .addComponent(jlbHoTen)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jlbHoTen)
                .addGap(29, 29, 29)
                .addComponent(jlbMaSV)
                .addGap(35, 35, 35)
                .addComponent(jlbLop)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtThoat)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        new Menu_TaiKhoan_SV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public void hienThi() {
   
        ArrayList<KetQuaHocTap> list = KetQuaController.getAll(DangNhap.maSV);
        jlbHoTen.setText("Họ tên:" + list.get(0).getTenSV());
        jlbMaSV.setText("Mã sinh viên:" + list.get(0).getMaSV());
        jlbLop.setText("Lớp:" + list.get(0).getTenLop());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("STT");
        model.addColumn("Tên môn học");
        model.addColumn("Điểm TX1");
        model.addColumn("Điểm TX2");
        model.addColumn("Điểm giữa kỳ");
        model.addColumn("Điểm TB");
        model.addColumn("Số tiết nghỉ");
        model.addColumn("ĐK dự thi");

        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                (i + 1), list.get(i).getTenMon(), list.get(i).getDiemTX1(), list.get(i).getDdiemTX2(),
                list.get(i).getDiemGiuaKy(), list.get(i).getDiemTrungBinh(), list.get(i).getSoTietNghi(),
                list.get(i).getDieuKienDuThi()
            });
        }
        jTable1.setModel(model);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTapSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTapSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTapSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTapSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KetQuaHocTapSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JLabel jlbHoTen;
    private javax.swing.JLabel jlbLop;
    private javax.swing.JLabel jlbMaSV;
    // End of variables declaration//GEN-END:variables
}
