/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.JOptionPane;

/**
 *
 * @author Lê Dũng
 */
public class Menu_TaiKhoan_GV extends javax.swing.JFrame {

    /**
     * Creates new form TaiKhoan_GV
     */
    public Menu_TaiKhoan_GV() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiDangXuat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiNhapKQHocTap = new javax.swing.JMenuItem();
        jmiNhapDiemThi = new javax.swing.JMenuItem();
        jQuanLylopHoc = new javax.swing.JMenu();
        jmiQuanLySinhVien = new javax.swing.JMenuItem();
        jmiQuanLyMonHoc = new javax.swing.JMenuItem();
        jmiQuanLylophoc = new javax.swing.JMenuItem();
        jmiQuanLyGiangVien = new javax.swing.JMenuItem();
        jmiQuanLyKhoa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-ngang.png"))); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jmiDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log out.png"))); // NOI18N
        jmiDangXuat.setText("Đăng xuất");
        jmiDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDangXuat);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Quản lý điểm");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jmiNhapKQHocTap.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiNhapKQHocTap.setText("Nhập điểm học phần");
        jmiNhapKQHocTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapKQHocTapActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNhapKQHocTap);

        jmiNhapDiemThi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiNhapDiemThi.setText("Nhập điểm thi");
        jmiNhapDiemThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemThiActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNhapDiemThi);

        jMenuBar1.add(jMenu2);

        jQuanLylopHoc.setBorder(null);
        jQuanLylopHoc.setText("Quản lý");
        jQuanLylopHoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jQuanLylopHoc.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jmiQuanLySinhVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiQuanLySinhVien.setText("Quản lý sinh viên");
        jmiQuanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLySinhVienActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jmiQuanLySinhVien);

        jmiQuanLyMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiQuanLyMonHoc.setText("Quản lý môn học");
        jmiQuanLyMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLyMonHocActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jmiQuanLyMonHoc);

        jmiQuanLylophoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiQuanLylophoc.setText("Quản lý lớp học");
        jmiQuanLylophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLylophocActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jmiQuanLylophoc);

        jmiQuanLyGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiQuanLyGiangVien.setText("Quản lý giảng viên");
        jmiQuanLyGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLyGiangVienActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jmiQuanLyGiangVien);

        jmiQuanLyKhoa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jmiQuanLyKhoa.setText("Quản lý khoa");
        jmiQuanLyKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLyKhoaActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jmiQuanLyKhoa);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem1.setText("Quản lý tài khoản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jQuanLylopHoc.add(jMenuItem1);

        jMenuBar1.add(jQuanLylopHoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDangXuatActionPerformed
        int cont = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất?","Đăng xuất",JOptionPane.YES_NO_OPTION);
        if(cont==JOptionPane.YES_OPTION){
            new DangNhap().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jmiDangXuatActionPerformed

    private void jmiNhapKQHocTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapKQHocTapActionPerformed
        new NhapKetQuaHocTap().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiNhapKQHocTapActionPerformed

    private void jmiNhapDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemThiActionPerformed
        new NhapKetQuaThi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiNhapDiemThiActionPerformed

    private void jmiQuanLyMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLyMonHocActionPerformed
        new quanlymonhoc().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiQuanLyMonHocActionPerformed

    private void jmiQuanLylophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLylophocActionPerformed
        new quanlylop().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiQuanLylophocActionPerformed

    private void jmiQuanLyGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLyGiangVienActionPerformed
        new GiangVienForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiQuanLyGiangVienActionPerformed

    private void jmiQuanLyKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLyKhoaActionPerformed
        new KhoaForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiQuanLyKhoaActionPerformed

    private void jmiQuanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLySinhVienActionPerformed
        new NhapThongTinSinhVien().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiQuanLySinhVienActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new quanlytaikhoan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_TaiKhoan_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_TaiKhoan_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_TaiKhoan_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_TaiKhoan_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_TaiKhoan_GV().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jQuanLylopHoc;
    private javax.swing.JMenuItem jmiDangXuat;
    private javax.swing.JMenuItem jmiNhapDiemThi;
    private javax.swing.JMenuItem jmiNhapKQHocTap;
    private javax.swing.JMenuItem jmiQuanLyGiangVien;
    private javax.swing.JMenuItem jmiQuanLyKhoa;
    private javax.swing.JMenuItem jmiQuanLyMonHoc;
    private javax.swing.JMenuItem jmiQuanLySinhVien;
    private javax.swing.JMenuItem jmiQuanLylophoc;
    // End of variables declaration//GEN-END:variables
}
