package View;

import Controller.KetQuaController;
import Model.KetQuaHocTap;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PV
 */
public class NhapKetQuaHocTap extends javax.swing.JFrame {

    /**
     * Creates new form NhapKetQuaHocTap
     */
    public NhapKetQuaHocTap() {
        initComponents();
        setLocationRelativeTo(null);
        loadMaMonHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbMaMH = new javax.swing.JComboBox<>();
        jtfDiemTX1 = new javax.swing.JTextField();
        jtfDiemTX2 = new javax.swing.JTextField();
        jtfDiemHS2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfSoTietNghi = new javax.swing.JTextField();
        jcbDKDuThi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jlbTrangThai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfTenMonHoc = new javax.swing.JTextField();
        jtfTenSV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtNhap = new javax.swing.JButton();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jtfThoat = new javax.swing.JButton();
        jtfMaSV = new javax.swing.JTextField();
        jbtXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập kết quả học tập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã môn học");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tên môn học");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Điểm thường xuyên 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Điểm thường xuyên 2");

        jcbMaMH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMaMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaMHActionPerformed(evt);
            }
        });

        jtfDiemTX1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfDiemTX2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfDiemHS2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Điểm hệ số 2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Số tiết nghỉ");

        jtfSoTietNghi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jcbDKDuThi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbDKDuThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đủ điệu kiện", "Không đủ điều kiện" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Điều kiện dự thi");

        jlbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã sinh viên");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tên sinh viên");

        jtfTenMonHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfTenMonHoc.setEnabled(false);

        jtfTenSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfTenSV.setAutoscrolls(false);
        jtfTenSV.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbtNhap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        jbtNhap.setText("Nhập");
        jbtNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNhapActionPerformed(evt);
            }
        });

        jbtThem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jtfThoat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jtfThoat.setText("Thoát");
        jtfThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfThoatActionPerformed(evt);
            }
        });

        jtfMaSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaSVActionPerformed(evt);
            }
        });

        jbtXoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        jbtXoa.setText("Xóa");
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbMaMH, 0, 215, Short.MAX_VALUE)
                            .addComponent(jtfTenMonHoc))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenSV)
                            .addComponent(jtfMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDiemTX1)
                            .addComponent(jtfDiemTX2)
                            .addComponent(jtfDiemHS2)
                            .addComponent(jtfSoTietNghi)
                            .addComponent(jcbDKDuThi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbTrangThai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(jbtNhap)
                .addGap(55, 55, 55)
                .addComponent(jbtThem)
                .addGap(60, 60, 60)
                .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jtfThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfDiemTX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDiemTX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfDiemHS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfSoTietNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbDKDuThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNhap)
                    .addComponent(jbtThem)
                    .addComponent(jbtSua)
                    .addComponent(jtfThoat)
                    .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jlbTrangThai)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaMHActionPerformed
        String ma = jcbMaMH.getSelectedItem().toString();
        jtfTenMonHoc.setText(KetQuaController.getTenMonHoc(ma));
        ArrayList<KetQuaHocTap> list = KetQuaController.getSVTheoMonHoc(ma);
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("STT");
        model.addColumn("Mã sinh viên");
        model.addColumn("Họ tên");
        model.addColumn("Điểm TX1");
        model.addColumn("Điểm TX2");
        model.addColumn("Điểm HS2");
        model.addColumn("Điểm TB");
        model.addColumn("Số tiết nghỉ");
        model.addColumn("ĐK dự thi");

        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                (i + 1), list.get(i).getMaSV(), list.get(i).getTenSV(), list.get(i).getDiemTX1(), list.get(i).getDdiemTX2(),
                list.get(i).getDiemGiuaKy(), list.get(i).getDiemTrungBinh(), list.get(i).getSoTietNghi(),
                list.get(i).getDieuKienDuThi()
            });
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_jcbMaMHActionPerformed

    private void jbtNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNhapActionPerformed
        jcbMaMH.setSelectedIndex(0);
        jtfTenMonHoc.setText("");
        jtfMaSV.setText("");
        jtfTenSV.setText("");
        jtfDiemTX1.setText("");
        jtfDiemHS2.setText("");
        jtfDiemTX2.setText("");
        jcbDKDuThi.setSelectedIndex(0);
        jtfSoTietNghi.setText("");
        jlbTrangThai.setText("");
        jcbMaMH.setSelectedIndex(0);
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
    }//GEN-LAST:event_jbtNhapActionPerformed

    private void jtfMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaSVActionPerformed
        String ma = jtfMaSV.getText();
        jtfTenSV.setText(KetQuaController.getTenSinhVien(ma));
    }//GEN-LAST:event_jtfMaSVActionPerformed

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        try {
            String maSV = jtfMaSV.getText();
            Double diemTX1 = Double.parseDouble(jtfDiemTX1.getText());
            Double diemTX2 = Double.parseDouble(jtfDiemTX2.getText());
            Double diemHS2 = Double.parseDouble(jtfDiemHS2.getText());
            int soTietNghi = Integer.parseInt(jtfSoTietNghi.getText());
            if (maSV.equals("") || jtfDiemTX1.getText().equals("") || jtfDiemTX2.getText().equals("") || jtfDiemHS2.getText().equals("") || jtfSoTietNghi.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Dữ liệu khoogn để trônghs", "Lỗi", JOptionPane.CANCEL_OPTION);
                throw new Exception();
            }
            if (diemTX1 > 10 || diemTX1 < 0 || diemHS2 > 10 || diemHS2 < 0 || diemTX2 > 10 || diemTX2 < 0) {
                JOptionPane.showMessageDialog(this, "Điểm không hợp lệ", "Lỗi", JOptionPane.CANCEL_OPTION);
                throw new Exception();
            }
            KetQuaHocTap s = new KetQuaHocTap();
            s.setMaSV(maSV);
            s.setMaMon(jcbMaMH.getSelectedItem().toString());
            s.setHocKy(KetQuaController.getHocKy(jcbMaMH.getSelectedItem().toString()));
            s.setDiemTX1(diemTX1);
            s.setDdiemTX2(diemTX2);
            s.setDiemGiuaKy(diemHS2);
            Double dtb = (Double.parseDouble(jtfDiemTX1.getText()) + Double.parseDouble(jtfDiemTX2.getText()) + Double.parseDouble(jtfDiemHS2.getText()) * 2) / 4;
            s.setDiemTrungBinh(dtb);
            s.setSoTietNghi(soTietNghi);
            s.setDieuKienDuThi(jcbDKDuThi.getSelectedItem().toString());
            s.setDiemThi(null);
            s.setDiemChu(null);
            s.setDiemTK10(null);
            s.setDiemTK4(null);
            s.setXepLoai(null);
            s.setTenSV(jtfTenSV.getText());
            s.setTenMon(jtfTenMonHoc.getText().toString());
            s.setMaLop(null);
            s.setTenLop(null);
            KetQuaController.setDiemTrenLop(s);
            jcbMaMHActionPerformed(evt);
            jlbTrangThai.setText("Thêm thành công!");
            jlbTrangThai.setForeground(Color.green);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.CANCEL_OPTION);
            jlbTrangThai.setText("Thêm thất bại!");
            jlbTrangThai.setForeground(Color.red);
        }
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        try {
            String maSV = jtfMaSV.getText().trim();
            Double diemTX1 = Double.parseDouble(jtfDiemTX1.getText());
            Double diemTX2 = Double.parseDouble(jtfDiemTX2.getText());
            Double diemHS2 = Double.parseDouble(jtfDiemHS2.getText());
            int soTietNghi = Integer.parseInt(jtfSoTietNghi.getText());
            if (maSV.equals("") || jtfDiemTX1.getText().trim().equals("") || jtfDiemTX2.getText().trim().equals("") || jtfDiemHS2.getText().trim().equals("") || jtfSoTietNghi.getText().trim().equals("")) {
                throw new Exception("Không để trống dữ liệu");
            }
            KetQuaHocTap s = new KetQuaHocTap();
            s.setMaSV(maSV);
            s.setMaMon(jcbMaMH.getSelectedItem().toString());
            s.setHocKy(KetQuaController.getHocKy(jcbMaMH.getSelectedItem().toString()));
            s.setDiemTX1(diemTX1);
            s.setDdiemTX2(diemTX2);
            s.setDiemGiuaKy(diemHS2);
            Double dtb = (Double.parseDouble(jtfDiemTX1.getText()) + Double.parseDouble(jtfDiemTX2.getText()) + Double.parseDouble(jtfDiemHS2.getText()) * 2) / 4;
            s.setDiemTrungBinh(dtb);
            s.setSoTietNghi(soTietNghi);
            s.setDieuKienDuThi(jcbDKDuThi.getSelectedItem().toString());
            s.setDiemThi(null);
            s.setDiemChu(null);
            s.setDiemTK10(null);
            s.setDiemTK4(null);
            s.setXepLoai(null);
            s.setTenSV(jtfTenSV.getText());
            s.setTenMon(jtfTenMonHoc.getText().toString());
            s.setMaLop(null);
            s.setTenLop(null);
            KetQuaController.updateDiemTrenLop(s);
            jcbMaMHActionPerformed(evt);
            jlbTrangThai.setText("Sửa thành công!");
            jlbTrangThai.setForeground(Color.green);
            jcbMaMHActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.CANCEL_OPTION);
            jlbTrangThai.setText("Sửa thất bại!");
            jlbTrangThai.setForeground(Color.red);
        }
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jtfThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfThoatActionPerformed
        new Menu_TaiKhoan_GV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jtfThoatActionPerformed

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        try {
            String masv = jtfMaSV.getText().trim();
            String mamh = jcbMaMH.getSelectedItem().toString();
            if (jtfTenMonHoc.getText().trim().equals("")) {
                throw new Exception("Không để trống mã môn học");
            }
            if (masv.equals("")) {
                throw new Exception("Không để trống mã sinh viên");
            }

            int click = JOptionPane.showConfirmDialog(null, "Xóa sinh viên mã: " + masv + "?", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.YES_OPTION) {
                KetQuaController.delete(mamh, masv);
                jlbTrangThai.setText("Xóa sinh viên thành công");
                jlbTrangThai.setForeground(Color.green);
                jcbMaMHActionPerformed(evt);
            } else {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.CANCEL_OPTION);
            jlbTrangThai.setText("Sửa thất bại!");
            jlbTrangThai.setForeground(Color.red);
        }
    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        jtfMaSV.setText(jTable1.getValueAt(row, 1).toString());
        jtfTenSV.setText(jTable1.getValueAt(row, 2).toString());
        jtfDiemTX1.setText(jTable1.getValueAt(row, 3).toString());
        jtfDiemTX2.setText(jTable1.getValueAt(row, 4).toString());
        jtfDiemHS2.setText(jTable1.getValueAt(row, 5).toString());
        jtfSoTietNghi.setText(jTable1.getValueAt(row, 7).toString());
        jcbDKDuThi.setSelectedItem(jTable1.getValueAt(row, 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {

            //java.util.jtfDiemTX1ger.getLogger(NhapKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapKetQuaHocTap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtNhap;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JComboBox<String> jcbDKDuThi;
    private javax.swing.JComboBox<String> jcbMaMH;
    private javax.swing.JLabel jlbTrangThai;
    private javax.swing.JTextField jtfDiemHS2;
    private javax.swing.JTextField jtfDiemTX1;
    private javax.swing.JTextField jtfDiemTX2;
    private javax.swing.JTextField jtfMaSV;
    private javax.swing.JTextField jtfSoTietNghi;
    private javax.swing.JTextField jtfTenMonHoc;
    private javax.swing.JTextField jtfTenSV;
    private javax.swing.JButton jtfThoat;
    // End of variables declaration//GEN-END:variables

    private void loadMaMonHoc() {
        ArrayList<String> listMH = KetQuaController.getMaMonHoc();
        for (String i : listMH) {
            jcbMaMH.addItem(i);
        }

    }

}
