/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.KetQuaController;
import Model.KetQuaHocTap;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PV
 */
public class NhapKetQuaThi extends javax.swing.JFrame {

    /**
     * Creates new form NhapKetQuaThi
     */
    public NhapKetQuaThi() {
        initComponents();
        setLocationRelativeTo(null);
        loadMaMonHoc();
    }

    private void loadMaMonHoc() {
        ArrayList<String> listMH = KetQuaController.getMaMonHoc();
        for (String i : listMH) {
            jcbMaMH.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jtfThoat = new javax.swing.JButton();
        jlbTrangThai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbMaMH = new javax.swing.JComboBox<>();
        jtfTenMH = new javax.swing.JTextField();
        jtfMaSV = new javax.swing.JTextField();
        jtfHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDiemThi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập kết quả thi");

        jtfNhap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        jtfNhap.setText("Nhập");
        jtfNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhapActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã môn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên Môn");

        jbtThem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jtfThoat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jtfThoat.setText("Thoát");
        jtfThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfThoatActionPerformed(evt);
            }
        });

        jlbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã sinh viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên sinh viên");

        jcbMaMH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMaMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaMHActionPerformed(evt);
            }
        });

        jtfTenMH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfTenMH.setEnabled(false);

        jtfMaSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaSVActionPerformed(evt);
            }
        });

        jtfHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfHoTen.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Điểm thi");

        jtfDiemThi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbTrangThai))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfTenMH)
                                            .addComponent(jcbMaMH, 0, 196, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(jtfMaSV)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jtfDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jtfNhap)
                .addGap(99, 99, 99)
                .addComponent(jbtThem)
                .addGap(98, 98, 98)
                .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jtfThoat)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtThem)
                    .addComponent(jbtSua)
                    .addComponent(jtfThoat)
                    .addComponent(jtfNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jlbTrangThai)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaSVActionPerformed
        String ma = jtfMaSV.getText();
        jtfHoTen.setText(KetQuaController.getTenSinhVien(ma));
    }//GEN-LAST:event_jtfMaSVActionPerformed

    private void jcbMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaMHActionPerformed
        String ma = jcbMaMH.getSelectedItem().toString();
        jtfTenMH.setText(KetQuaController.getTenMonHoc(ma));
        ArrayList<KetQuaHocTap> list = KetQuaController.getSVTheoMonHoc(ma);
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("STT");
        model.addColumn("Mã sinh viên");
        model.addColumn("Họ tên");
        model.addColumn("Điểm TB trên lớp");
        model.addColumn("Điểm Thi");
        model.addColumn("Điểm tổng kết 10");
        model.addColumn("Điểm tổng kết 4");
        model.addColumn("Điểm chữ");
        model.addColumn("Xếp loại");
        model.addColumn("Ghi chú");
        for (int i = 0; i < list.size(); i++) {
            String dthi, d10, d4;
            if (list.get(i).getDiemThi() < 0) {
                dthi = "";
            } else {
                dthi = (String) (list.get(i).getDiemThi().toString());
            }
            ///////////////
            if (list.get(i).getDiemTK10() < 0) {
                d10 = "";
            } else {
                d10 = (String) (list.get(i).getDiemTK10().toString());
            }
            /////////////

            if (list.get(i).getDiemTK4() < 0) {
                d4 = "";
            } else {
                d4 = (String) (list.get(i).getDiemTK4().toString());
            }
            if (list.get(i).getDieuKienDuThi().equals("Không đủ điều kiện")) {
                model.addRow(new Object[]{
                    (i + 1), list.get(i).getMaSV(), list.get(i).getTenSV(), list.get(i).getDiemTrungBinh(),
                    "x", "x", "x",
                    "x", "x", "Học lại"
                });
            } else if (list.get(i).getDiemTK10()<4 && !d10.equals("")) {
                model.addRow(new Object[]{
                    (i + 1), list.get(i).getMaSV(), list.get(i).getTenSV(), list.get(i).getDiemTrungBinh(),
                    dthi, d10, d4,
                    list.get(i).getDiemChu(), list.get(i).getXepLoai(), "Học lại"
                });
            }
            else{
                    model.addRow(new Object[]{
                    (i + 1), list.get(i).getMaSV(), list.get(i).getTenSV(), list.get(i).getDiemTrungBinh(),
                    dthi, d10, d4,
                    list.get(i).getDiemChu(), list.get(i).getXepLoai(), ""
                });
            }
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_jcbMaMHActionPerformed

    private void jtfNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhapActionPerformed
        jcbMaMH.setSelectedIndex(0);
        jtfTenMH.setText("");
        jtfMaSV.setText("");
        jtfHoTen.setText("");
        jtfDiemThi.setText("");
    }//GEN-LAST:event_jtfNhapActionPerformed

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        try {
            String maSV = jtfMaSV.getText();
            Double diemThi = Double.parseDouble(jtfDiemThi.getText());
            String maMH = jcbMaMH.getSelectedItem().toString();
            if (maSV.equals("") || jtfDiemThi.getText().equals("") || jtfTenMH.getText().equals("")) {
                throw new Exception("Nhập đầy đủ dữ liệu");
            }
            KetQuaHocTap s = KetQuaController.getSV(maSV, maMH);
            if (s.getDieuKienDuThi().equals("Không đủ điều kiện")) {
                throw new Exception("Sinh viên không đủ điều kiện dự thi");
            }
            if (s == null) {
                throw new Exception("Sinh viên chưa học môn này");
            }
            Double diemTK10 = (s.getDiemGiuaKy() + diemThi * 2) / 3;
            s.setDiemTK10(diemTK10);
            String xepLoai, dChu;
            Double diemTK4;
            if (diemThi < 0 || diemThi > 10) {
                throw new Exception("Điểm thi không hợp lệ");
            }
            if (diemTK10 < 4) {
                xepLoai = "Kém";
                dChu = "F";
                diemTK4 = 0.0;
            } else if (diemTK10 < 4.7) {
                xepLoai = "Trung bình yếu";
                dChu = "D";
                diemTK4 = 1.0;
            } else if (diemTK10 < 5.5) {
                xepLoai = "Trung bình yếu";
                dChu = "D+";
                diemTK4 = 1.5;
            } else if (diemTK10 < 6.2) {
                xepLoai = "Trung bình";
                dChu = "C";
                diemTK4 = 2.0;
            } else if (diemTK10 < 7.0) {
                xepLoai = "Trung bình";
                dChu = "C+";
                diemTK4 = 2.5;
            } else if (diemTK10 < 7.7) {
                xepLoai = "Khá";
                dChu = "B";
                diemTK4 = 3.0;
            } else if (diemTK10 < 8.5) {
                xepLoai = "Khá";
                dChu = "B+";
                diemTK4 = 3.5;
            } else {
                xepLoai = "Giỏi";
                dChu = "A";
                diemTK4 = 4.0;
            }
            s.setDiemThi(diemThi);
            s.setDiemTK10(diemTK10);
            s.setDiemTK4(diemTK4);
            s.setDiemChu(dChu);
            s.setXepLoai(xepLoai);
            KetQuaController.insertDiemThi(s);
            jcbMaMHActionPerformed(evt);
            jlbTrangThai.setText("Thêm thành công!");
            jlbTrangThai.setForeground(Color.green);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
            jlbTrangThai.setText("Thêm thất bại!");
            jlbTrangThai.setForeground(Color.red);
        }
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        jbtThemActionPerformed(evt);
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jtfThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfThoatActionPerformed
        new Menu_TaiKhoan_GV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jtfThoatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        jtfMaSV.setText(jTable1.getValueAt(row, 1).toString());
        jtfHoTen.setText(jTable1.getValueAt(row, 2).toString());
        jtfDiemThi.setText(jTable1.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapKetQuaThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapKetQuaThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JComboBox<String> jcbMaMH;
    private javax.swing.JLabel jlbTrangThai;
    private javax.swing.JTextField jtfDiemThi;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMaSV;
    private javax.swing.JButton jtfNhap;
    private javax.swing.JTextField jtfTenMH;
    private javax.swing.JButton jtfThoat;
    // End of variables declaration//GEN-END:variables
}
