package View;

import Controller.lopcontroller;
import Model.Khoa;
import Model.lophoc;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tuan Bao
 */
public class quanlylop extends javax.swing.JFrame {

    /**
     * Creates new form lop
     */
    lopcontroller db = new lopcontroller();

    public quanlylop() {
        initComponents();
        hienThi();
        laykhoa();
        setLocationRelativeTo(null);
    }

    private lophoc getlopDetail() {
        String Malop = txtmalop.getText().trim();
        String Telop = txttenlop.getText().trim();
        String makhoa = cbmakhoa.getSelectedItem().toString().trim();
        return new lophoc(Malop, Telop, makhoa);
    }

    public void clearTextDetail() {

        txttenlop.setText("");
        txtmalop.setText("");

    }

    public void hienThi() {
        ArrayList<lophoc> list = lopcontroller.getAll();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Lớp");
        model.addColumn("Tên Lớp");
        model.addColumn("Mã Khoa");
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getMaLop(), list.get(i).getTenLop(), list.get(i).getMaKhoa()
            });
        }
        jtblop.setModel(model);
    }

    public void laykhoa() {
        ArrayList<Khoa> list = lopcontroller.getkhoa();
        for (int i = 0; i < list.size(); i++) {
            cbmakhoa.addItem(list.get(i).getMaKhoa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmalop = new javax.swing.JTextField();
        txttenlop = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblop = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jbThoat = new javax.swing.JButton();
        cbmakhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã lớp ");

        jLabel2.setText("Tên lớp");

        jLabel3.setText("Mã khoa");

        jtblop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblop);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("THÔNG TIN LỚP HỌC");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });

        cbmakhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmakhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jbThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txttenlop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(txtmalop, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmakhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(jbThoat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnxoa)
                    .addComponent(cbmakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblopMouseClicked
        // TODO add your handling code here:
        int row = jtblop.getSelectedRow();
//        //thí sinh trên dòng chọn chính là bản ghi tứ i trong dsts
        txtmalop.setText(jtblop.getValueAt(row, 0).toString());

        txttenlop.setText(jtblop.getValueAt(row, 1).toString());
        cbmakhoa.setSelectedItem(jtblop.getValueAt(row, 2).toString());

    }//GEN-LAST:event_jtblopMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        try {
            //lấy dòng chọn trong table
            if (txtmalop.getText().trim().equals("") || txttenlop.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "bạn phải nhập đẩy đủ thông tin");
            } else {
                lophoc lh = new lophoc();
                lh.setMaLop(txtmalop.getText().trim());
                lh.setTenLop(txttenlop.getText().trim());
                lh.setMaKhoa(cbmakhoa.getSelectedItem().toString().trim());
                boolean tb = db.Add(lh);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "thêm thất bại");
                }
                //lấy lại dữ liệu cho bảng
                hienThi();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " + ex.toString());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        try {
            //lấy dòng chọn trong table
            int row = jtblop.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "bạn cần chọn một dòng để sửa");
            } else {
                lophoc lh = new lophoc();
                lh.setMaLop(txtmalop.getText().trim());
                lh.setTenLop(txttenlop.getText().trim());
                lh.setMaKhoa(cbmakhoa.getSelectedItem().toString().trim());
                boolean tb = db.update(lh);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "sửa thất bại");
                }
                //lấy lại dữ liệu cho bảng
                hienThi();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " + ex.toString());
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try {
            int click = JOptionPane.showConfirmDialog(null, "Chắc chắn môn học này", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.YES_OPTION) {
                //lấy dòng chọn hiện thời trong table
                int row = jtblop.getSelectedRow();
                //lấy số báo danh ở cột 0
                String malop = jtblop.getValueAt(row, 0).toString();
                //truyền vào phognf thi xóa theo sbd
                lophoc lh = getlopDetail();
                db.delete(lh);
                hienThi();
                clearTextDetail();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không xóa được " + ex.toString());
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        // TODO add your handling code here:
        new Menu_TaiKhoan_GV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbThoatActionPerformed

    private void cbmakhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmakhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmakhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlylop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlylop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlylop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlylop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlylop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbmakhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbThoat;
    private javax.swing.JTable jtblop;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txttenlop;
    // End of variables declaration//GEN-END:variables
}
