package View;

import Controller.Monhoccontroller;
import Model.Khoa;
import Model.monhoc;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tuan Bao
 */
public class quanlymonhoc extends javax.swing.JFrame {

    /**
     * Creates new form mamon
     */
    Monhoccontroller db = new Monhoccontroller();
    public quanlymonhoc() {
        initComponents();
        hienThi();
        laykhoa();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbmon = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmamon = new javax.swing.JTextField();
        txttenmon = new javax.swing.JTextField();
        txtsotc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtThoat = new javax.swing.JButton();
        cbmakhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Môn");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên Môn");

        jtbmon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbmon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbmonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbmon);

        jLabel3.setText("Mã khoa");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("THÔNG TIN MÔN HỌC");

        txtmamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmamonActionPerformed(evt);
            }
        });

        jLabel5.setText("Số TC");

        jbtThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        cbmakhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmakhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsotc, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(txttenmon)
                    .addComponent(txtmamon)
                    .addComponent(cbmakhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jbtThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(jbtThoat))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnthem)
                        .addGap(36, 36, 36)
                        .addComponent(btnsua)
                        .addGap(31, 31, 31)
                        .addComponent(btnxoa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmamon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsotc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbmakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private monhoc getmonDetail() {
        String Mamon = txtmamon.getText().trim();
        String Tenmon = txttenmon.getText().trim();
        int sotc = Integer.parseInt(txtsotc.getText().trim());
        String makhoa = cbmakhoa.getSelectedItem().toString().trim();
        return new monhoc(Mamon, Tenmon, sotc, makhoa);
    }
    public void laykhoa(){
        ArrayList<Khoa> list = Monhoccontroller.getkhoa();
        for (int i = 0; i < list.size(); i++) {
            cbmakhoa.addItem(list.get(i).getMaKhoa());
        }
    }
    public void clearTextDetail() {
        
        txttenmon.setText("");
        txtmamon.setText("");
        txtsotc.setText("");
        
    }
    public void hienThi() {
        ArrayList<monhoc> list = Monhoccontroller.getAll();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Môn");
        model.addColumn("Tên Môn");
        model.addColumn("Số tin chỉ");
        model.addColumn("Mã khoa");
        
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getMaMon(), list.get(i).getTenMon(), list.get(i).getSoTC(),list.get(i).getMaKhoa()
            });
        }
        jtbmon.setModel(model);
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        try{
            //lấy dòng chọn trong table
            if(txtmamon.getText().trim().equals("") || txttenmon.getText().trim().equals("") || txtsotc.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane,"bạn phải nhập đẩy đủ thông tin");
            }
            else {
                monhoc lh = new monhoc();
            lh.setMaMon(txtmamon.getText().trim());
            lh.setTenMon(txttenmon.getText().trim());
            lh.setSoTC(Integer.parseInt(txtsotc.getText().trim()));
            lh.setMaKhoa(cbmakhoa.getSelectedItem().toString().trim());
            boolean tb=db.Add(lh);
            if (tb) {
                JOptionPane.showMessageDialog(rootPane,"Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane,"thêm thất bại");
            }
            //lấy lại dữ liệu cho bảng
            hienThi();
                
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " + ex.toString());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        try{
            int row = jtbmon.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "bạn cần chọn một dòng để sửa");
            }
            else{
                monhoc lh = new monhoc();
            lh.setMaMon(txtmamon.getText().trim());
            lh.setTenMon(txttenmon.getText().trim());
            lh.setSoTC(Integer.parseInt(txtsotc.getText().trim()));
            lh.setMaKhoa(cbmakhoa.getSelectedItem().toString().trim());
            boolean tb=db.update(lh);
            if (tb) {
                JOptionPane.showMessageDialog(rootPane,"sửa thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane,"sửa thất bại");
            }
            //lấy lại dữ liệu cho bảng
            hienThi(); 
            }
            //lấy dòng chọn trong table
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " );
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try{
            int click = JOptionPane.showConfirmDialog(null, "Chắc chắn môn học này", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.YES_OPTION) {
                //lấy dòng chọn hiện thời trong table
                int row = jtbmon.getSelectedRow();
                //lấy số báo danh ở cột 0
                String mamon = jtbmon.getValueAt(row, 0).toString();
                //truyền vào phognf thi xóa theo sbd
                monhoc lh = getmonDetail();
                db.delete(lh);
                hienThi();
                clearTextDetail();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không xóa được " + ex.toString());
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jtbmonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbmonMouseClicked
        // TODO add your handling code here:
        int row = jtbmon.getSelectedRow();
        //        //thí sinh trên dòng chọn chính là bản ghi tứ i trong dsts
        txtmamon.setText(jtbmon.getValueAt(row, 0).toString());

        txttenmon.setText(jtbmon.getValueAt(row, 1).toString());
        txtsotc.setText(jtbmon.getValueAt(row, 2).toString());
        
        cbmakhoa.setSelectedItem(jtbmon.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jtbmonMouseClicked

    private void txtmamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmamonActionPerformed

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        new Menu_TaiKhoan_GV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtThoatActionPerformed

    private void cbmakhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmakhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmakhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlymonhoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlymonhoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlymonhoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlymonhoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlymonhoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbmakhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JTable jtbmon;
    private javax.swing.JTextField txtmamon;
    private javax.swing.JTextField txtsotc;
    private javax.swing.JTextField txttenmon;
    // End of variables declaration//GEN-END:variables
}
