/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.taikhoancontroller;
import Model.TaiKhoan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Bao
 */
public class quanlytaikhoan extends javax.swing.JFrame {

    /**
     * Creates new form quanlytaikhoan
     */
    public quanlytaikhoan() {
        initComponents();
        hienThi();
        setLocationRelativeTo(null);
    }
    taikhoancontroller db = new taikhoancontroller();


    private TaiKhoan gettkDetail() {
        String tentaikhoan = txttentaikhoan.getText().trim();
        String matkhau = txtmatkhau.getText().trim();
        String masinhvien = txtmasinhvien.getText().trim();
        return new TaiKhoan(tentaikhoan, matkhau, tentaikhoan,masinhvien);
       }

    public void clearTextDetail() {

        txttentaikhoan.setText("");
        txtmatkhau.setText("");

    }

    public void hienThi() {
        ArrayList<TaiKhoan> list = taikhoancontroller.getAll();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Tên tài khoản");
        model.addColumn("Mật khẩu");
        model.addColumn("quyền truy cập");
        model.addColumn("mã sinh viên");
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getTenTaiKhoan(), list.get(i).getMatKhau(), list.get(i).getQuyenTruyCap(),list.get(i).getMasinhvien()
            });
        }
        jtbtaikhoan.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttentaikhoan = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbtaikhoan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtmasinhvien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên tài khoản");

        jLabel2.setText("Mật khẩu");

        jtbtaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbtaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbtaikhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbtaikhoan);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("THÔNG TIN TÀI KHOẢN");

        jbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã sinh viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbThoat)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(jLabel4)
                    .addGap(113, 113, 113))
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel2)
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txttentaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(txtmatkhau))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(77, 77, 77)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbThoat)
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnthem))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsua))
                    .addGap(18, 18, 18)
                    .addComponent(btnxoa)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        try {
            //lấy dòng chọn trong table
            if (txttentaikhoan.getText().trim().equals("") || txtmatkhau.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "bạn phải nhập đẩy đủ thông tin");
            } else {
                TaiKhoan lh = new TaiKhoan();
                lh.setTenTaiKhoan(txttentaikhoan.getText().trim());
                lh.setMatKhau(txtmatkhau.getText().trim());
                lh.setMasinhvien(txtmasinhvien.getText().trim());
                lh.setQuyenTruyCap("Sinhvien");
                boolean tb = db.Add(lh);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "thêm thất bại");
                }
                //lấy lại dữ liệu cho bảng
                hienThi();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " + ex.toString());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        try {
            //lấy dòng chọn trong table
            int row = jtbtaikhoan.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "bạn cần chọn một dòng để sửa");
            } else {
                TaiKhoan lh = new TaiKhoan();
                lh.setTenTaiKhoan(txttentaikhoan.getText().trim());
                lh.setMatKhau(txtmatkhau.getText().trim());
                lh.setMasinhvien(txtmasinhvien.getText().trim());
              
                boolean tb = db.update(lh);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "sửa thất bại");
                }
                //lấy lại dữ liệu cho bảng
                hienThi();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không sửa được " + ex.toString());
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try {
            int click = JOptionPane.showConfirmDialog(null, "Chắc chắn môn học này", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.YES_OPTION) {
                //lấy dòng chọn hiện thời trong table
                int row = jtbtaikhoan.getSelectedRow();
                //lấy số báo danh ở cột 0
                String tentaikhoan = jtbtaikhoan.getValueAt(row, 0).toString();
                //truyền vào phognf thi xóa theo sbd
                TaiKhoan lh = gettkDetail();
                db.delete(lh);
                hienThi();
                clearTextDetail();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không xóa được " + ex.toString());
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jtbtaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbtaikhoanMouseClicked
        // TODO add your handling code here:
        int row = jtbtaikhoan.getSelectedRow();
        //        //thí sinh trên dòng chọn chính là bản ghi tứ i trong dsts
        txttentaikhoan.setText(jtbtaikhoan.getValueAt(row, 0).toString());

        txtmatkhau.setText(jtbtaikhoan.getValueAt(row, 1).toString());
        
        txtmasinhvien.setText(jtbtaikhoan.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_jtbtaikhoanMouseClicked

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        // TODO add your handling code here:
        new Menu_TaiKhoan_GV().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlytaikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbThoat;
    private javax.swing.JTable jtbtaikhoan;
    private javax.swing.JTextField txtmasinhvien;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txttentaikhoan;
    // End of variables declaration//GEN-END:variables
}
